name: footify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  shared_preferences: ^2.5.3
  url_launcher: ^6.1.10
  font_awesome_flutter: ^10.1.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  provider: ^6.1.1
  http: ^1.1.0
  flutter_web_plugins:
    sdk: flutter
  flutter_cors: ^1.5.0
  image_picker: ^0.8.4+4
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  table_calendar: ^3.0.9
  flutter_native_splash: ^2.3.10
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^19.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend-Bold.ttf
        - asset: assets/fonts/Lexend-ExtraBold.ttf
        - asset: assets/fonts/Lexend-Light.ttf
        - asset: assets/fonts/Lexend-Medium.ttf
        - asset: assets/fonts/Lexend-SemiBold.ttf

flutter_localizations:
  sdk: flutter
  generate: true

flutter_native_splash:
  color_dark: "#1D1D1D"  # Dark mode background
  color: "#FFFFFF"       # Light mode background
  image: assets/images/footify_logo_optimized_light.svg
  image_dark: assets/images/footify_logo_optimized_dark.svg
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: contain
  fullscreen: true
  android_12:
    image: assets/images/Footify-Logo-NoBG_szerk_hosszu_logo-01.png
    image_dark: assets/images/Footify-Logo-NoBG.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#1D1D1D"

