// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAlreR-jF2vcQDGH0hW6KakLoHcznnCWU',
    appId: '1:1061851623185:web:4ce6ed93056299857fa6b0',
    messagingSenderId: '1061851623185',
    projectId: 'footify-13da4',
    authDomain: 'footify-13da4.firebaseapp.com',
    storageBucket: 'footify-13da4.firebasestorage.app',
    measurementId: 'G-HD8BT3062N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsfTqXzL1q7XYFn_Ke6gwng4FpV5eI-gQ',
    appId: '1:1061851623185:android:376ed506468d7ba47fa6b0',
    messagingSenderId: '1061851623185',
    projectId: 'footify-13da4',
    storageBucket: 'footify-13da4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArjQATHMx0ck4kMF0RpkiYygLjFBNc5WI',
    appId: '1:1061851623185:ios:15af8c5260c344127fa6b0',
    messagingSenderId: '1061851623185',
    projectId: 'footify-13da4',
    storageBucket: 'footify-13da4.firebasestorage.app',
    iosBundleId: 'com.example.footify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArjQATHMx0ck4kMF0RpkiYygLjFBNc5WI',
    appId: '1:1061851623185:ios:15af8c5260c344127fa6b0',
    messagingSenderId: '1061851623185',
    projectId: 'footify-13da4',
    storageBucket: 'footify-13da4.firebasestorage.app',
    iosBundleId: 'com.example.footify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAlreR-jF2vcQDGH0hW6KakLoHcznnCWU',
    appId: '1:1061851623185:web:a7bb2765e604d7397fa6b0',
    messagingSenderId: '1061851623185',
    projectId: 'footify-13da4',
    authDomain: 'footify-13da4.firebaseapp.com',
    storageBucket: 'footify-13da4.firebasestorage.app',
    measurementId: 'G-M02TZ9TLL4',
  );

}